# Generated by Django 5.2.12 on 2026-03-25 03:46

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('display_name', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/')),
                ('avatar_url', models.URLField(blank=True, default='', max_length=512)),
                ('bio', models.TextField(blank=True, default='', max_length=500)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not', 'Prefer Not to Say')], default='', max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('user_language', models.CharField(default='en', max_length=10)),
                ('user_timezone', models.CharField(default='UTC', max_length=64)),
                ('preferences', models.JSONField(default=account.models.default_preferences)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_deleted', 'created_at'], name='idx_acct_deleted_created')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_deleted', False), models.Q(('deleted_at__isnull', False), ('is_deleted', True)), _connector='OR'), name='chk_acct_deleted_at_set')],
            },
        ),
    ]
