# Generated by Django 5.2.12 on 2026-03-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userauth',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
